---
- hosts: workstations
  vars_files:
    - vars/slurm.yml
    - vars/kernel-nvidia.yml
  strategy: free
  become: yes
  roles:
    - bodsch.snapd
    - mambaorg.micromamba
    - common
    - workstation

- hosts: computenodes
  become: yes
  roles:
    - bodsch.snapd
    - mambaorg.micromamba
    - common
- hosts: userservers
  vars_files:
    - vars/slurm.yml
  become: yes
  roles:
    - userserver
