---
- hosts: workstations
  vars_files:
    - vars/slurm.yml
  strategy: free
  become: yes
  roles:
    - bodsch.snapd
    - common
    - workstation

- hosts: compute_nodes
  become: yes
  roles:
    - bodsch.snapd
    - common

- hosts: servers
  become: yes
  roles:
    - bodsch.snapd
    - common

- hosts: user_servers
  become: yes
  roles:
    - bodsch.snapd
    - common

- hosts: storage_servers
  become: yes
  roles:
    - bodsch.snapd
#    - common

- hosts: vms
  become: yes
  roles:
    - bodsch.snapd
#    - common

