---
- hosts: workstations
  vars_files:
    - vars/slurm.yml
    - vars/kernel-nvidia.yml
  strategy: free
  become: yes
  roles:
    - {role: apt-proxy, tags: always}   # must precede every role that touches apt
    - mambaorg.micromamba
    - common
    - workstation

- hosts: computenodes
  become: yes
  roles:
    - {role: apt-proxy, tags: always}   # must precede every role that touches apt
    - mambaorg.micromamba
    - common
