---
- hosts: workstations
  vars_files:
    - vars/slurm.yml
  strategy: free
  become: yes
  roles:
    - bodsch.snapd
    - common
    - workstation

- hosts: computenodes
  become: yes
  roles:
    - bodsch.snapd
    - common

- hosts: servers
  become: yes
  roles:
    - bodsch.snapd
    - common

- hosts: userservers
  become: yes
  roles:
    - bodsch.snapd
    - common

- hosts: storageservers
  become: yes
  roles:
    - bodsch.snapd
#    - common

- hosts: vms
  become: yes
  roles:
    - bodsch.snapd
#    - common

