---

- name: Get logged-in users (excluding Ansible executor) count
  ansible.builtin.shell: |
    who | awk '{print $1}' | grep -v localadmin | sort -u | wc -l
  register: logged_in_users_count
  changed_when: false  # This task never changes system state

- name: Unhold packages
  command: >
    apt-mark unhold '*nvidia*' 'linux*'
  when:
    - not (logged_in_users_count.stdout | int > 0)

- name: Remove nvidia and kernel
  command: >
    apt-get --autoremove -y purge '*xanmod*' '*nvidia*'
  when:
    - not (logged_in_users_count.stdout | int > 0)

- name: Install or upgrade kernels
  ansible.builtin.apt:
    state: latest
    allow_change_held_packages: true
    pkg:
      - linux-zabbly
  register: kernel_installed
  when:
    - not (logged_in_users_count.stdout | int > 0)

- name: Check if nvidia-driver is needed
  ansible.builtin.shell: |
    ubuntu-drivers list | cut -d, -f1 | grep -v server | sort -V | tail -1 | grep nvidia-driver
  ignore_errors: true
  register: nvidia_driver_needed
  changed_when: false  # This task never changes system state

- name: Install or upgrade nvidia driver
  ansible.builtin.apt:
    name:  "{{ nvidia_driver_needed.stdout }}"
    state: latest
    allow_change_held_packages: true
  register: nvidia_installed
  when:
    - nvidia_driver_needed.rc == 0
    - not (logged_in_users_count.stdout | int > 0)

- name: Rebuild all dkms packages
  ansible.builtin.shell: |
    ls /boot/initrd.img-* | cut -d- -f2- | xargs -n1 /usr/lib/dkms/dkms_autoinstaller start
  when:
    - nvidia_driver_needed.rc == 0
    - (nvidia_installed.changed | default(false)) or (kernel_installed.changed | default(false))

- name: Hold kernel and nvidia
  command: >
    apt-mark hold '*nvidia*' 'linux*'
