---

- name: disable adding vscode repo
  debconf: name='code' question='code/add-microsoft-repo' value='false' vtype='select'

- name: accept mscorefonts
  debconf: name='ttf-mscorefonts-installer' question='msttcorefonts/accepted-mscorefonts-eula' value='true' vtype='select'

- name: Install workstation apt packages
  apt:
    update_cache: yes
    state: present
    pkg:
      - zoom
      - firefox
      - meld
      - gnuplot-qt
      - yubikey-manager
      - libpam-yubico
      - libpam-u2f
      - yubioath-desktop
      - texlive-full
      - x2goserver
      - x2goclient
      - x2goserver-xsession
      - x2golxdebindings
      - language-pack-en
      - language-pack-fr
      - language-pack-gnome-en
      - language-pack-gnome-fr
      - feh
      - xfig
      - lxqt-core
      - lxde-core
      - google-chrome-stable
      - hunspell-en-ca
      - hunspell-en-gb
      - hunspell-en-med
      - hunspell-fr
      - libreoffice
      - flatpak
      - default-jre
      - obs-studio
      - speedcrunch
      - flameshot
      - peek
      - xclip
      - xsel
      # Globus connect personal
      - tk
      - tcllib
      # VMWARE Connect
      - libudev0
      - flameshot
      - dconf-editor
      - pspp
      - sassc
      - autokey-gtk
      - virtualgl
#KDE specific
      - partitionmanager
      - kubuntu-restricted-addons
      - kubuntu-restricted-extras
      - kolourpaint
      - libreoffice-style-breeze
      - krita
      - kdenlive
# Remote access
      - xpra
# Alternative interfaces
      - i3

- name: remove problematic software
  apt: pkg={{ item }} state=absent update_cache=no cache_valid_time=3600
  with_items:
    - ktorrent

- name: Install kernel and nvidia and hold
  ansible.builtin.script: bin/install_kernel.sh

- name: default firefox for browser
  community.general.alternatives:
    name: x-www-browser
    path: /usr/bin/firefox
