---

- name: disable adding vscode repo
  debconf: name='code' question='code/add-microsoft-repo' value='false' vtype='select'

- name: accept mscorefonts
  debconf: name='ttf-mscorefonts-installer' question='msttcorefonts/accepted-mscorefonts-eula' value='true' vtype='select'

- name: Install workstation apt packages
  apt:
    update_cache: yes
    state: present
    pkg:
      - bruno
      - wezterm
      - turbovnc
      - brave-browser
      - code
      - zoom
      - firefox
      - meld
      - gnuplot-qt
      - yubikey-manager
      - libpam-yubico
      - libpam-u2f
      - yubioath-desktop
      - texlive-full
      - feh
      - xfig
      - google-chrome-stable
      - hunspell-en-ca
      - hunspell-en-gb
      - hunspell-en-med
      - hunspell-fr
      - libreoffice
      - flatpak
      - default-jre
      - obs-studio
      - speedcrunch
      - flameshot
      - peek
      - xclip
      - xsel
      # Globus connect personal
      - tk
      - tcllib
      # VMWARE Connect
      - libudev0
      - dconf-editor
      - pspp
      - sassc
      - autokey-gtk
      - virtualgl
      - gparted
      - ubuntu-restricted-extras
      - ubuntu-restricted-addons
# Remote access tools
      - xpra
      - turbovnc
      - x2goserver
      - x2goclient
      - x2goserver-xsession
# Alternative interfaces
      - i3

- name: Install LXDE for remote connections
  apt:
    update_cache: yes
    state: present
    install_recommends: false
    pkg:
      - lxde-core
      - x2golxdebindings

- name: remove problematic software
  apt: pkg={{ item }} state=absent update_cache=no autoremove=true purge=true cache_valid_time=3600
  with_items:
    - ktorrent
    - hexchat
    - pidgin
    - transmission-gtk
    - transmission-common

- name: default brave for browser
  community.general.alternatives:
    name: x-www-browser
    path: /usr/bin/brave-browser
