#VMware is now Omnissa, URL for .deb   https://customerconnect.omnissa.com/downloads/details?downloadGroup=CART26FQ2_LIN64_DEBPKG_2506&productId=1616&rPId=119132

- name: Install VMware Horizon Client from local .deb
  ansible.builtin.apt:
    deb: "/data/scratch2/.ansible/omnissa/Omnissa-Horizon-Client-2506-8.16.0-16536624989.x64.deb"

- name: config vmware horizon client
  copy: src=files/view-mandatory-config dest=/etc/omnissa/horizon-default-config

- name: vmware daemon config
  copy: src=files/vmware_config dest=/etc/omnissa/horizon-mandatory-config
