- name: install vmware horizon debs
  apt: deb={{ item }}
  with_items:
    - https://download3.vmware.com/software/CART25FQ1_LIN64_DebPkg_2312.1/VMware-Horizon-Client-2312.1-8.12.1-23543969.x64.deb
  ignore_errors: yes

- name: config vmware horizon client
  copy: src=files/view-mandatory-config dest=/etc/vmware/

- name: vmware daemon config
  copy: src=files/vmware_config dest=/etc/vmware/config
