- name: Install Manual Deb Files
  apt: deb={{ item }}
  with_items:
    - https://github.com/fboender/ansible-cmdb/releases/download/1.31/ansible-cmdb-1.31.deb
    - https://github.com/sharkdp/bat/releases/download/v0.25.0/bat_0.25.0_amd64.deb
    - https://github.com/twpayne/chezmoi/releases/download/v2.61.0/chezmoi_2.61.0_linux_amd64.deb
    - https://github.com/bootandy/dust/releases/download/v1.1.2/du-dust_1.1.2-1_amd64.deb
    - https://github.com/lsd-rs/lsd/releases/download/v1.1.5/lsd_1.1.5_amd64_xz.deb
    - https://github.com/BurntSushi/ripgrep/releases/download/14.1.1/ripgrep_14.1.1-1_amd64.deb
    - https://downloads.rclone.org/v1.69.1/rclone-v1.69.1-linux-amd64.deb
    - https://github.com/kellyjonbrazil/jc/releases/download/v1.25.4/jc_1.25.4-1_amd64.deb
    - https://github.com/sharkdp/fd/releases/download/v10.2.0/fd_10.2.0_amd64.deb
  ignore_errors: yes
