---
- name: ensure /opt/pipx
  ansible.builtin.file:
    path: /opt/pipx
    state: directory
    mode: 0755

- name: install qbatch site-wide
  community.general.pipx:
    name: qbatch
    state: latest
  environment:
    PIPX_HOME: /opt/pipx
    PIPX_BIN_DIR: /usr/local/bin

- name: Install qbatch env var config
  copy: src=files/99qbatch.sh dest=/etc/profile.d/
