---
- name: Install Common APT Packages
  apt:
    update_cache: yes
    state: present
    pkg:
    - wdiff
    - pigz
    - micro
    - apptainer
    - autoconf-archive
    - fzf
    - pandoc
    - fd-find
    - python3-pip
    - neovim
    - btop
    - apt-file
    - lz4
    - nfs4-acl-tools
    - jq
    - mosh
    - fio
    - default-jre-headless
    - ccache
    - watchdog
    - mailutils
    - msmtp-mta
    - msmtp
    - htop
    - iotop-c
    - xauth
    - tmux
    - screen
    - imagemagick
    - exfatprogs
    - ntfs-3g
    - dosfstools
    - xfsprogs
    - reiserfsprogs
    - reiser4progs
    - kpartx
    - cryptsetup
    - openssh-server
    - parallel
    - quota
    - nmap
    - lrzip
    - p7zip-full
    - unace
    - unrar
    - zip
    - unzip
    - sharutils
    - rar
    - uudeview
    - mpack
    - arj
    - cabextract
    - gdebi-core
    - ansible
    - apparmor-profiles-extra
    - apparmor-profiles
    - smartmontools
    - squashfs-tools
    - aptitude
    - tree
    - unattended-upgrades
    - nvme-cli
    - ncdu
    - dcmtk
    - rename
    - libpam-tmpdir
    - libnss-myhostname
    - ethtool
#Development software
    - vim
    - emacs
    - git
#Docker
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin
#SLURM dependencies
    - libcurl4-openssl-dev
    - zlib1g-dev
    - libhwloc-dev
    - hwloc
    - libreadline-dev
    - libpam-dev
    - man2html-base
    - libmunge-dev
    - libmunge2
    - munge
